
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-cluster-deployment
spec:
  replicas: 2 # this should always be 1
  template:
    metadata:
      labels:
        app: mongo-cluster
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: pv0003
          mountPath: /mongodb/data
      volumes:
      - name: pv0003
        awsElasticBlockStore:
          volumeID: vol-03c34e54b456f88eb # volume id from aws console.
          fsType: ext4
