apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0003"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-03c34e54b456f88eb"
